INSERT INTO Airport(code,city,country,name) VALUES ('EWR','New Jersey','USA','Liberty International');
INSERT INTO Airport(code,city,country,name) VALUES ('BLR','Bengaluru','India','Kempegowda International');
INSERT INTO Airport(code,city,country,name) VALUES ('LHR','London','UK','Heathrow');
INSERT INTO Airport(code,city,country,name) VALUES ('DXB','Dubai','UAE','Dubai International');
INSERT INTO Airport(code,city,country,name) VALUES ('DEL','Delhi','India','Indira Gandhi International');
INSERT INTO Airport(code,city,country,name) VALUES ('BOM','Mumbai','India','Chatrapathi Shivaji International');
INSERT INTO Airport(code,city,country,name) VALUES ('MAA','Chennai','India','Chennai International');
INSERT INTO Airport(code,city,country,name) VALUES ('CCO','Kolkata','India','Netaji Subash Chandrabose');
INSERT INTO Airport(code,city,country,name) VALUES ('FCO','Rome','Italy','Leonardo da Vinci International');
INSERT INTO Airport(code,city,country,name) VALUES ('OSL','New York','USA','John F Kennedy International');
INSERT INTO Airport(code,city,country,name) VALUES ('CDG','Paris','France','Charles de Gaulle International');
INSERT INTO Airport(code,city,country,name) VALUES ('HND','Tokyo','Japan','Haneda');
INSERT INTO Airport(code,city,country,name) VALUES ('SYD','Sydney','Australia','Sydney International');
INSERT INTO Airport(code,city,country,name) VALUES ('BKK','Bangkok','Thailand','Suvarnabhoomi International');
INSERT INTO Airport(code,city,country,name) VALUES ('LGW','London','UK','Gatwick');
INSERT INTO Airport(code,city,country,name) VALUES ('SVO','Moscow','Russia','Sheremetyevo International');
INSERT INTO Airport(code,city,country,name) VALUES ('FRA','Frankfurt','Germany','Frankfurt');
INSERT INTO Airport(code,city,country,name) VALUES ('DOH','Doha','Qatar','Hamad International');
INSERT INTO Airport(code,city,country,name) VALUES ('ATL','Atlanta','USA','Hartsfield-Jackson International');
INSERT INTO Airport(code,city,country,name) VALUES ('AMS','Amsterdam','Netherlands','Schiphol');
INSERT INTO Airport(code,city,country,name) VALUES ('AUH','Abu Dhabi','UAE','Abu Dhabi Internation');
