INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','EK','Economy');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','EK','Business');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','EK','First');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','AI','Executive');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','AI','Maharaja');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','TG','Silk');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','TG','Premium');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','TG','Royal Silk');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','QR','Economy');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','QR','Business');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','QR','First');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','QA','Economy');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','QA','International');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','QA','First Suites');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','BA','Economy');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','BA','Club World');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','BA','Club');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Economy','EY','Economy');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('Business','EY','Pearl Business');
INSERT INTO Class(class_name,airline,particular_name) VALUES ('First','EY','The Residence');
